# Generated by Django 3.1.1 on 2020-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gopal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='office',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
