# Generated by Django 3.1.1 on 2020-09-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gopal', '0003_auto_20200905_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='city',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='src',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('value', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('name', 'id')},
        ),
    ]
