# Generated by Django 3.1.1 on 2020-09-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gopal', '0004_auto_20200905_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='value',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together=set(),
        ),
    ]
