# Generated by Django 3.1.1 on 2020-09-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gopal', '0005_auto_20200905_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='sizel',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='house',
            name='acres',
        ),
        migrations.RemoveField(
            model_name='house',
            name='position_lat',
        ),
        migrations.RemoveField(
            model_name='house',
            name='position_lng',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sizeh',
        ),
        migrations.RemoveField(
            model_name='house',
            name='square_footage',
        ),
    ]
