# Generated by Django 3.1.1 on 2020-09-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gopal', '0007_auto_20200913_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dateListed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='mediaURL',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='office',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='ownership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gopal.ownership'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
